/*
SPI - Serial Peripheral Interface
is a synchronous serial data protocol
Typically there are (at least) four lines for communication
- MISO (Master in Slave Out) - The Slave line for sending data to the master (not required for pure output)
On Arduino Uno: PIN 12 or ICSP-1
- MOSI (Master Out Slave in) - The Master Line for sending data to the peripherals
On Arduino Uno: PIN 11 or ICSP-4  --> Connected to TPICB595 Pin SER IN
- SCK (Serial Clock) - The clock pulses which synchronize data transmission generated by the master
On Arduino Uno: PIN 13 or ICSP-3 --> Connected to TPIC595 Pin SRCK
- SS (Slave Select) - the pin on each device that the master can use to enable and disable specific devices
Can be any Pin, usually Pin 10 because it is close to the other connectors
--> Connected to TPIC595 Pin RCK
Typically you will have one SS-line for each slave device.
*/


// include the SPI library:
#include <PolpoShifter.h>


// set pin 10 as the slave select for the digital pot:
const int confirmTransmissionPin = 10;

Shifter PolpoShifter(1, confirmTransmissionPin);  

void setup() {
  // set the slaveSelectPin as an output:
}

void loop() {
  delay(10);
  // go through the six channels of the digital pot:
  for (int i = 0; i < 10; i++) {
    PolpoShifter.displayOneDigit(i);
    delay(500);
  }

}


